NVIDIA/Megatron-LM

mpu/random.py
=> Support latest PyTorch RNG state API.

megatron/arguments.py
This is a very trivial change. A help message for distributed args is wrong. `title` parameter is changed from `mixed precision` to `distributed`.
=> Change distributed argument group title to appropriate one.

megatron/arguments.py
The `--split` help message contains literal `%` which is in conflict with `%`-formatting. Due to this reason, `--help` on a Megatron-LM application fails. The literal `%` should be escaped with `%%`.
```
$ python some_megatron_application.py --help
...
TypeError: %o format: an integer is required, not dict
```
=> Escape % in --split help message

examples/pretrain_bert_distributed_with_mp.sh
The `--seq-length` argument was missing from the example distributed BERT pre-training script which throws an error while attempting to parse the arguments as the code expects all arguments to be specified and have a non-`None` value. By updating the example variables at the top of the script and running it, the application will quickly error out with the following stack unless the `--seq-length` argument is specified:
```
AssertionError
Traceback (most recent call last):
File "pretrain_bert.py", line 146, in <module>
pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
File "/workspace/megatron-lm/megatron/training.py", line 94, in pretrain
initialize_megatron(extra_args_provider=extra_args_provider,
File "/workspace/megatron-lm/megatron/initialize.py", line 51, in …
```
=> Add seq-length argument to distribued BERT example

megatron/mpu/initialize.py
Some tests expect a clean model parallel slate and complain if a previous test left something behind; this change clears more variables that the tests complain about.
=> Destroy more groups in `destroy_model_parallel`

README.md
PP seems to have been added in https://github.com/NVIDIA/Megatron-LM/commit/46c74b4ca06a7794db1e2615544095535cdf12c2, so I think this clause is not accurate anymore
=> Strike note that PP is not supported for T5 in README.md

README.md, megatron/arguments.py, megatron/model/transformer.py
We add an option to use FlashAttention in Megatron-LM.
Cc @ekelsen
=> Integrate FlashAttention into Megatron-LM

tools/checkpoint_loader_megatron.py, tools/checkpoint_saver_megatron.py
When use swiglu, checkpoint_util.py only handle the mlp weight concatenation and forget to handle the mlp bias. It will cause incorrect inference result after merging checkpoints.
=> [Fix] mlp-bias concatenation in checkpoint_util when using swiglu

megatron/core/transformer/transformer_config.py
In the new `TransformerConfig`, when `--recompute-granularity` is set, it is checked whether `--recompute-method` is in allowed the values and not `None`. However, when `--recompute-granularity selective` is used, `--recompute-method` _must not_ be set (i.e. it must be `None`) according to `megatron/arguments.py`.
=> Fix wrong config check

megatron/core/pipeline_parallel/schedules.py
`decoder_seq_len` was unconditionally divided before. When using a decoder-only model, this variable may not be set and just `seq_len` may be given (`seq_len` is also what's used a few lines below the modified code in the decoder-only case).
=> Only regard decoder sequence length when using an encoder-decoder

megatron/model/transformer.py
It's a bug in `FlashSelfAttention` class.
Once you run `forward` in eval mode, `dropout_p` will become 0 forever, even you turn back to training mode.
=> bug fix: when eval, dropout_p turns to 0 forever

tools/checkpoint_saver_megatron.py
**Describe**
The `world_size` of `margs` will be overwritten by `checkpoint_args` in `tools/checkpoint_saver_megatron.py`.
**To Reproduce**
1. Produce a ckpt by global_batch_size =24,  micro_batch_size=1, data_parallel_size =2, tensor_model_parallel_size=4, pipeline_model_paralell_size=2
2. Convert the ckpt to target_tensor_parallel_size=1, target_pipeline_paralell_size=1 by using `tools/checkpoint_util.py
`
3. Get assertion error `assert global_batch_size % micro_batch_times_data_parallel == 0` in `megatron/microbatches.py
`
=> Skip 'world_size' instead of coping from checkpint args.

megatron/arguments.py
if key is not in args, the getattr will throw expection.
=> fix the getattr use

megatron/arguments.py, megatron/optimizer_param_scheduler.py, megatron/training.py
Allows starting linear warmup from a value other than 0. Backward-compatible due to the default of 0.0, except for the API change. If you'd like, I can also add the new argument in a backward-compatible way; however, I thought the positioning made sense this way. (The order initial LR, max LR, min LR follows the temporal evolution.) :)
=> Allow setting initial warmup LR

megatron/core/pipeline_parallel/schedules.py
This is an equivalent of [this commit](https://github.com/NVIDIA/Megatron-LM/commit/32bbb76d5767fdbf8dc60d4ef07d103cef8aca02), but applied to old MCore
=> Fix bug in distopt allgathers with interleaved pipeline parallelism for old MCore

megatron/model/fused_layer_norm.py, megatron/utils.py
The data preprocessing step doesn't require GPUs, but it requires some utility modules which unnecessarily import `apex` package and then fails where there's only CPU available.
Separately deploying data preprocessing and training on different environments would be a nice feature for developers. This pull request fixes that by lazily import (evaluate the availability) those symbols and suggests installing apex when they are required but not found.
=> "Lazy" import symbols from apex to make data preprocess can run without GPUs

megatron/core/parallel_state.py
The NCCL communicator configs are set as default values. So, when not specifying the config values using env vars, communicators become initialized with default NCCL communicator settings.
=> Add interface to specify NCCL configs of each communicator

megatron/core/transformer/transformer_layer.py
With SwiGLU, the weights of `dense_h_to_4h` (linear_fc1) must be first chunked into 2 and then TP-sharded.
This MR implements it for **inference**.
The optimizer state requires some additional handling.
=> Fix SwiGLU with dist checkpoint for inference

megatron/initialize.py
Indented the init_distributed in initialize.py, to the else path of `if torch.distributed.is_initialized(),` such that it's only executed if torch distributed is really not initialized.
When initializing the process group manually, it will be executed a second time due to the missing indent.
This Leads to a `RuntimeError: trying to initialize the default process group twice!`
=> Indented torch.init_distributed()

megatron/model/language_model.py, megatron/model/transformer.py
Missing Import for Rotary Position Embedding.
Missing rotary_percent argument when instanciating RotaryEmbeddings
=> fix: rotary position embedding missing argument

megatron/model/transformer.py
There are unnecessary repeat_interleave when  `self.num_attention_heads_per_partition == self.num_query_groups_per_partition` in attention.py and transformer.py, which will trigger torch.repeat_interleave even when repeat==1, which hurt the performance when `self.num_attention_heads_per_partition == self.num_query_groups_per_partition`.
=> Remove unnecessary repeat_interleave to fix performance drop
